# See the configuration reference at https://symfony.com/bundles/SchebTwoFactorBundle/6.x/configuration.html
scheb_two_factor:
    security_tokens:
        # - Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken
        - Symfony\Component\Security\Http\Authenticator\Token\PostAuthenticationToken
    totp:
        enabled: false                  # If TOTP authentication should be enabled, default false
        server_name: Server Name       # Server name used in QR code
        issuer: Issuer Name            # Issuer name used in QR code
        window: 1                      # How many codes before/after the current one would be accepted as valid
        parameters:                    # Additional parameters added in the QR code
            image: 'https://my-service/img/logo.png'
        template: totp/login.html.twig   # Template used to render the authentication form          
    email:
        enabled: true                  # If email authentication should be enabled, default false
        sender_email: swiftride2023@gmaiL.com   # Sender email address
        sender_name: 2fa          # Sender name
        digits: 4                      # Number of digits in authentication code
   # trusted_device:
    #    enabled: true                  # If the trusted device feature should be enabled
     #   lifetime: 5184000              # Lifetime of the trusted device cookie
     #   extend_lifetime: false
     #   key: cc21ed8d4b2a28a1f14028428fd3b5e5scheb
     #   cookie_name: trusted_device    # Name of the trusted device cookie
     #   cookie_secure: false           # Set the 'Secure' (HTTPS Only) flag on the trusted device cookie
      #  cookie_same_site: "lax"        # The same-site option of the cookie, can be "lax" or "strict"

